# 9. Обработка ошибок

```
try {
    notExistingFunction();
}
catch (e) {
    console.log(e);
}
finally {
    console.log('finally!');
}
```